# Generated by Django 5.1.2 on 2024-10-21 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='available_copiess',
        ),
    ]
